### ISSUE TITLE
Error: [blastdbcmd]

### ISSUE THREAD

**Issue by llk15** [pylelab/rMSA#1]
**what do these errors mean?**

Error: [blastdbcmd] Skipped NJGU01000008.1
Error: [blastdbcmd] Skipped NJIH01000006.1
Error: [blastdbcmd] Skipped NJIH01000007.1
Error: [blastdbcmd] Skipped NMUI01000258.1
Error: [blastdbcmd] Skipped NNAY01000028.1
Error: [blastdbcmd] Skipped U00096.2
Error: [blastdbcmd] Skipped URS0000D65980_12908
Error: [blastdbcmd] Skipped URS0000D65CE5_12908
Error: [blastdbcmd] Skipped URS0000D66367_12908
Error: [blastdbcmd] Skipped URS0000D6690B_12908
Error: [blastdbcmd] Skipped URS0000D66E23_12908
Error: [blastdbcmd] Skipped URS0000D6710A_12908
Error: [blastdbcmd] Skipped URS0000D67735_12908
Error: [blastdbcmd] Skipped URS0000D678D0_12908
Error: [blastdbcmd] Skipped URS0000D6849F_12908
Error: [blastdbcmd] Skipped URS0000D68F86_12908
Error: [blastdbcmd] Skipped URS0000D695D1_12908
Error: [blastdbcmd] Skipped URS0000D69AE5_12908
Error: [blastdbcmd] Skipped URS0000D69C8A_12908
Error: [blastdbcmd] Skipped URS0000D6A10A_12908
Error: [blastdbcmd] Skipped URS0000D6A1FC_12908
Error: [blastdbcmd] Skipped URS0000D6A9A3_12908
Error: [blastdbcmd] Skipped URS0000D6ADD7_12908
Error: [blastdbcmd] Skipped URS0000D6B460_12908
Error: [blastdbcmd] Skipped URS0000D6B5DE_12908
Error: [blastdbcmd] Skipped URS0000D6BE97_12908
Error: [blastdbcmd] Skipped URS0000D6C3A3_12908
Error: [blastdbcmd] Skipped URS0000D6CB96_12908

**Comment by kad-ecoli** [comment]
They are warnings, not error. You should still be able to get the MSA.
