### ISSUE TITLE
Files are downloaded but not handled

### ISSUE THREAD

**Issue by pcs-jim** [pylelab/rMSA#3]
In the download.sh file, the Rfam.full_region.gz and the rfam_annotations.tsv.gz are downloaded. However in the curate.sh file, there is no code to handle these files. So, when running update.sh these files are just left there. Are they not needed or was there supposed to be code to handle these files?

**Comment by kad-ecoli** [comment]
They are directly used by rMSA.pl without the need to reformatting by curate.sh
```perl
my $db0to1 ="$dbdir/rfam_annotations.tsv.gz";
my $db0to2 ="$dbdir/Rfam.full_region.gz";
```
