### ISSUE TITLE
Error: [blastdbcmd] Skipped SEQ_ACCESSION

### ISSUE THREAD

**Issue by ReaKal** [pylelab/rMSA#4]
I am facing the error:
Error: [blastdbcmd] Skipped SEQ_ACCESSION
67532 (!) times, when running:
path/to/rMSA/bin/blastdbcmd -db path/to/rMSA/database/nt -entry_batch tmp/user/rMSA_38167_200247988/rfam2.0.list.split.aa -out /tmp/user/rMSA_38167_200247988/rfam2.0.db.aa

What could have gone wrong? Thank you!

**Comment by kad-ecoli** [comment]
That is not an error. You may simply ignore it.

**Comment by ReaKal** [comment]
I am also receiving an empty alingment file (only the query sequence is in the file), which means that alignment was not successful. 
Should I start another issue for this?
